package com.example.ecommerce.inventory.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    INVENTORY_ITEM_NOT_FOUND,
    INSUFFICIENT_INVENTORY,
    INVALID_STOCK_QUANTITY,
    DUPLICATE_RESERVATION_PRODUCT,
    RESERVATION_NOT_FOUND,
    RESERVATION_CONFLICT,
    INVALID_RESERVATION_STATE,
    DATA_INTEGRITY_CONFLICT,
    ENDPOINT_NOT_FOUND,
    INTERNAL_ERROR
}
