package com.example.ecommerce.order.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    INVALID_IDENTITY,
    UNAUTHORIZED,
    FORBIDDEN,
    ORDER_NOT_FOUND,
    INVALID_ORDER_ITEM,
    IDEMPOTENCY_KEY_CONFLICT,
    PRODUCT_CATALOG_UNAVAILABLE,
    ORDER_VERSION_CONFLICT,
    DATA_INTEGRITY_CONFLICT,
    ENDPOINT_NOT_FOUND,
    INTERNAL_ERROR
}
